# Generated by Django 4.0.4 on 2022-06-07 17:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
