# Generated by Django 4.0.4 on 2022-06-23 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_message_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='users',
            new_name='user',
        ),
    ]
